In [20]:
import numpy as np
import matplotlib.pyplot as plt
import os,sys
import os.path

乘法层（MulLayer）

In [21]:
class MulLayer:

    #初始化、前向传播、反向传播
    
    def __init__(self) -> None:
        self.x = None
        self.y = None

    def forward(self,x,y):
        self.x = x
        self.y = y
        out = x*y
        
        return out
    
    #dout为上游传来的导数
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        
        return dx,dy

In [22]:
apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple,apple_num)
price = mul_tax_layer.forward(apple_price,tax)

price

220.00000000000003

In [23]:
dprice = 1
dapple_price,dtax = mul_tax_layer.backward(dprice)
dapple,dapple_num = mul_apple_layer.backward(dapple_price)


dapple,dapple_num,dtax

(2.2, 110.00000000000001, 200)

加法层（AddLayer）

In [24]:
class AddLayer:
    def __init__(self) -> None:
        pass

    def forward(self,x,y):
        out = x+y
        return out
    
    def backward(self,dout):
        dx = dout * 1
        dy = dout * 1

        return dx,dy
        

In [25]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_sumtax_layer = MulLayer()


In [26]:
apple_price = mul_apple_layer.forward(apple,apple_num)
orange_price = mul_orange_layer.forward(orange,orange_num)
all_price = add_apple_orange_layer.forward(apple_price,orange_price)
price = mul_tax_layer.forward(all_price,tax)

dprice = 1
dall_price,dtax = mul_tax_layer.backward(dprice)
dapple_price,dorange_price = add_apple_orange_layer.backward(dall_price)
dorange,dorange_num = mul_orange_layer.backward(dorange_price)
dapple,dapple_num = mul_apple_layer.backward(dapple_price)

price,dapple,dapple_num,dorange,dorange_num,dtax


(715.0000000000001, 2.2, 110.00000000000001, 3.3000000000000003, 165.0, 650)

ReLU层

In [27]:
class Relu:
    def __init__(self) -> None:
        self.mask = None

    #传入的x不是单个值 简单比大小就可以的 所以需要mask进行处理
    def forward(self,x):
        self.mask = (x<=0)
        out = x.copy()
        out[self.mask] = 0

    #mask是由True/False构成的Numpy数组，会把正向传播时
    #输入x中<=0的地方保存为True，其他地位False
    #mask和x尺寸一样
        return out
    
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [28]:
x = np.array([[1.0,-0.5],[-2.0,3.0]])
mask = (x<=0)
x,mask,x[mask]

(array([[ 1. , -0.5],
        [-2. ,  3. ]]),
 array([[False,  True],
        [ True, False]]),
 array([-0.5, -2. ]))

Sigmoid层

In [29]:
class Sigmoid:
    def __init__(self) -> None:
        self.out = None

    def forward(self,x):
        out = 1/(1+np.exp(-x))
        return out
    
    def backward(self,dout):
        dx = dout * self.out * (1-self.out)
        return dx

Affine层\
神经网络的正向传播中进行的矩阵乘积运算在几何领域被称为仿射变换 因此称为Affine层

In [30]:
x_dot_w = np.array([[0,0,0],[10,10,10]])
b = np.array([1,2,3])
x_dot_w,x_dot_w+b
                   

(array([[ 0,  0,  0],
        [10, 10, 10]]),
 array([[ 1,  2,  3],
        [11, 12, 13]]))

矩阵的导数 和矩阵的尺寸一样 所以偏置b的导数 是把dy第0轴进行求和

In [31]:
class Affine:
    def __init__(self,w,b) -> None:
        self.w = w
        self.b = b
        self.x = None
        self.dw = None
        self.db = None

    def forward(self,x):
        self.x = x
        out = np.dot(x,self.w)+self.b

    def backward(self,dout):
        dx = np.dot(dout,self.w.T)
        self.dw = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)

        return dx

In [32]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        max_x = np.max(x,axis=0)
        x = x-max_x
        y = np.exp(x)/np.sum(np.exp(x),axis=0)

        return y.T
    
    max_x = np.max(x)
    x = x-max_x
    y = np.exp(x)/np.sum(np.exp(x))

def cross_entropy_error(y,t):
    delta = 1e-4
    if y.ndim == 1:
        y = y.reshape(1,y.size)
        t = t.reshape(1,t.size)

    batch_size = y.shape[0]

    if y.size == t.size:
        t = np.argmax(t,axis=1)#t = t.argmax(axis = 1)

    return -np.sum(np.log(y[np.arange(batch_size),t]+delta))/batch_size

In [33]:
class SoftmaxWithLoss:
    def __init__(self) -> None:
        self.loss = None
        self.y = None
        self.t = None

    def forward(self,x,t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y,self.t)

        return self.loss
    
    def backward(self,dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t)/batch_size
        return dx

In [34]:
class TwoLayerNet:
    def __ini

SyntaxError: invalid syntax (4020871865.py, line 2)