In [2]:
import numpy as np

In [6]:
a = [1,2,3,4]
b = [2,3,4,5]
x = np.array(a)
y = np.array(b)

In [5]:
x,type(x),type(a)

(array([1, 2, 3, 4]), numpy.ndarray, list)

进行计算的两个array元素个数需相同

In [7]:
x+y,x-y

(array([3, 5, 7, 9]), array([-1, -1, -1, -1]))

In [8]:
x*y,x/y

(array([ 2,  6, 12, 20]),
 array([0.5       , 0.66666667, 0.75      , 0.8       ]))

array和单一数值/标量进行计算 各个元素和该标量计算  广播

In [9]:
x*2

array([2, 4, 6, 8])

Numpy的N维数组  .shape 矩阵形状  .dtype 矩阵元素数据类型

In [12]:
a = np.array([[1,2],[3,4]])
a,a.shape,a.dtype

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 dtype('int32'))

In [13]:
b = np.array([[2,0],[0,3]])
b,b.shape,b.dtype

(array([[2, 0],
        [0, 3]]),
 (2, 2),
 dtype('int32'))

In [16]:
a+b,a-b

(array([[3, 2],
        [3, 7]]),
 array([[-1,  2],
        [ 3,  1]]))

In [18]:
a*b

array([[ 2,  0],
       [ 0, 12]])

In [19]:
a*2

array([[2, 4],
       [6, 8]])

Numpy中不同形状的数组也能计算 广播

b会变成和a相同的形状 再对应元素进行计算

In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])
a*b

array([[10, 40],
       [30, 80]])

访问元素

In [21]:
x = np.array([[1,2],[3,4],[5,6]])
x,x.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

In [23]:
x[0],x[0][0],x[1],x[1][1]

(array([1, 2]), 1, array([3, 4]), 4)

In [24]:
for i in x:
    print(i)

[1 2]
[3 4]
[5 6]


转化为一维数组

In [25]:
y = x.flatten()

In [27]:
x,type(x),y,type(y)

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 numpy.ndarray,
 array([1, 2, 3, 4, 5, 6]),
 numpy.ndarray)

In [30]:
y[np.array([1,2,3])]

array([2, 3, 4])

In [31]:
y>3

array([False, False, False,  True,  True,  True])

In [32]:
y[y>3]

array([4, 5, 6])